-- # Below, is the entire RS killfeed file, it's a hell, so, like, lock tf in lo
-- File checked by @CametizedDev

game.ReplicatedStorage["Display Message"].OnClientEvent:Connect(function(message,killer,extra,sound,color)

	local killMessagePool = {
		killer.." dominated "..extra,
		killer.." killed "..extra,
		"ngl, "..extra.." died",
		killer.." slaughtered "..extra,
		extra.." got absolutely destroyed by "..killer,
		extra.." combusted",
		killer.." had a better gaming chair than "..extra,
		"this guy, "..extra..", laugh at them.",
		"oh my god.. "..extra.." backflipped...",
		extra.." went afk",
		extra.." was slain by "..killer,
		killer.." L4D2 workshop'd "..extra,
		extra.." decided to take a very long nap",
		extra.." rage quit",
		extra.." went to the bathroom",
		killer.." abducted "..extra.." from the park",
		extra.." who?",
		extra.." no no wanna live anymore :(",
		"has anyone seen "..extra.."?",
		extra.." was a sore loser",
		extra.." ran into a piece of matter",
		extra.." was thrown through the wall by "..killer,
		'"killer.." put this message in quotes because of "..extra"',
		extra.." broke the fourth wall",
		killer.." screamed at "..extra,
		killer.." a",
		extra.." a",
		killer.." unplugged "..extra.."'s internet",
		killer.." dropkicked "..extra,
		killer.." threw bricks at "..extra.."'s house",
		killer.." threw rocks at "..extra,
		killer.." did something????",
		killer.." exploded "..extra..".. i think??",
		extra.." forgot to do /respawn",
		killer.." died. Oh wait, they actually caused the death of "..extra..", my bad.",
		extra.." flipped",
		extra.." was in the way of "..killer.."'s bullet",
		extra.." had immense skill issue ",
		killer.." was too sigma for " ..extra,
		killer.." was too BASED for " ..extra,
		extra.." has experienced peak vehicular manslaughter ",
		extra.." watched RECKLESS DRIVING ",
		"*car noises*",
		killer.." made " ..extra.. " alt tab out of a source game ",
		extra.." installed glue library ",
		extra.." didn't understand gun safety ",
		killer.." renewed their driver's license",
		extra.." had painful eye contact with "..killer,
		extra.." was too socially awkward for "..killer,
		killer.." sweats!!!!", --i cried
		extra.." pirated a nintendo game",  --beauty
		extra.." tried to update revolver showdown",
		extra.." was steve",
		--extra.." saw turtles' vrchat hours",
		killer.."'s aim is getting better",
		extra.." got a little too toxic on mic",
		extra.." played trepang¹",
		killer.." played trepang²",
		killer.." and " ..extra.. " played trepang³",
		extra.." was attacked by a horde of wolves",
		killer.." had a gun",
		'"I WILL END YOU" -'..killer.." 1985",
		killer.." doesn't even want "..extra.." around them",
		killer.." doesn't even want "..extra.." living in his apartment",
		extra.." spent too much on cs2 skins",
		--new ones start here
		-- i had fun -cam
		extra.." Womp",
		"*truck noises*",
		killer.." beep beeped like a sheep",
		extra.." liked trains more than "..killer.." ",
		extra.." isn't based!!!!!",
		extra.." just wanted his all knowing cat🤦🤦‍🤦‍🤦‍",
		killer.." launched an attack on "..extra.."'s home",
		extra.. " got 1984",
		extra.." AAAAAHHHHH",
		killer.." won the draw",
		'"I ALWAYS COME BACK -'..extra.." .",
		extra.." metal pipe",
		extra.." got served like a 5 michelin star meal by "..killer.." ",
		killer.." said 'boom' 5 times and killed "..extra.." ",
		extra.." coped and lost",
		killer.." hoped and won",
		extra.." tried fighting "..killer.." and got nothing out of it",
		killer.." had this feeling in his bones",
		killer.." was better unlike "..extra.." ",
		killer.." whacked "..extra.." with a hammer",
		extra.." had the worst desktop wallpaper",
		"'HOW MANY FORTNITE SKINS DO YOU OWN' -"..killer.." ",
		extra.." let the bird out of the cage",
		killer.." jumped",
		extra.." goes to ChickFilA on Sundays",
		extra.." played The Origin [LEGACY] by "..killer.." ",
		extra.." brought a Gnome across the entirety of Half Life 2 only to be met by "..killer.." ",
		extra.." tried to go to the moon, but they got grounded by "..killer.." .",
		extra.." wanted world peace, too bad that "..killer.." wanted war.",
		extra.." ran on a rope",
		killer.." got asked out by "..extra..".. You can understand how that went.",
		extra.." decided to look at those screenshots",
		killer.." lost his screenshots",
		extra.." broke tos",
		extra.." forgot to update his TextChatService",
		extra.." watched the vic clip because of "..killer,
		killer.." had LAYERS to it "..extra.. " said; 'say that again'",
		extra.." and "..killer.." played Nos Astra in TRIA.os",
		extra.." failed a Timestop in Phase 6 of Nos Astra",
		killer.." beat Nos Astra",
		killer.." moonwalked on "..extra,
		extra.." LOSES. THEY LOSE CAUSE " ..killer.. " is BETTER!!!",
		extra.." sploded",
		extra.." shook a pepsi can before opening it",
		extra.." used a purple vending machine",
		killer.." in an interview talks about their massive skill. Mentions how " ..extra.. " is kinda bad...",
		extra.." is gonna be an extra 3 ft tall next season because of "..killer,
		extra.." used 2022 materials in his new studio project",
		killer.." used a Lifeforce Potion on "..extra,
		extra.." played the calamity mod on death mode",
		killer.." smelled The Lud",
		killer.." had a DB_music in their back left pocket",
		extra.." took a deep breath through their forehead",
		killer.." achieved 'To The Moon' in TRIA.os",
		extra.." played Mango Obby by "..killer,
		extra.." refused to play Combat Initiation with "..killer,
		extra.." forgot to add guns because of "..killer,
		"bad",
		killer.." had some fun",
		extra.." looked at their camera roll",
		killer.." played Revolver Showdown",
		killer.." rigged " ..extra.. "'s instruments to fall while performing",
		killer.." bombed the house of "..extra,
		killer.." did something in 1999 :)",
		extra.." thought they found their father. nope. it was just "..killer.. ".", --depres
		extra.." played roblox on a 12 year old laptop",
		killer.." made "..extra.." fall off the wall",
		killer.." made "..extra.."'s day a little worse",
		extra.." played JToH instead of EToH",
		--extra.." made a VRChat account",
		killer.." jumped "..extra,
		extra.." missed",
		extra.." voted Cam for president instead of Fred",
		killer.." has swag compared to " ..extra,
		killer.." was Like Him",
		extra.." put ehan in the box",
		extra.." tripped",
		extra.." was tripped by " ..killer,
		extra.." asked for it from " ..killer,
		extra.." had a bugged train",
		killer.." threw a flash down A Long",
		extra.." was just a bit too slow..",
		extra.." watermelon",
		extra.." put too much glowstone in the respawn anchor",
		extra.." didn't know what to get " ..killer.. " for their birthday", -- 85
		extra.." got crushed by a big boulder",
		extra.." got a bit too close to the C.A.R.T.",
		killer.." WOAH! YOU'RE A KING!",
		-- help i dont know what to write lo
		killer.." bro KILLL bro",
		extra.." made some of the absolute WORST gameplay " ..killer.. " has seen in their LIFE.",
		extra.." didn't read the fine print",
		extra.." didn't have that awesome sauce within them",
		-- extra.." had a rat in their drink",
		killer.." broke it down for " ..extra,
		extra.." went into the goo lagoon ",
		"gaming",
		extra.." AAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHH",
		killer.." was the Imposter ",
		"Target " ..extra.. " eliminated.",
		killer.." DUNKED ON " ..extra, -- lololo im balalaing im baallling
		killer.." shatters eardrums ",
		extra.." got hit wit the waazoo",
		"'i'll ball you' - " ..extra,
		killer.." nae nae'd",
		"'I AM " ..killer.. ".' -Title Card",
		extra.." kicked from the gc",
		"in a shocking turn of events, " ..killer.. " is actually cooking!",
		killer.." made use of their surroundings to take out " ..extra,
		extra.." met their demise in a dramatic staring contest with " ..killer,
		killer.." won the staring contest",
		killer.." shot blindfolded and hit " ..extra,
		killer.." TRICKSHOT",
		killer.." used " ..extra.."'s own weapon against them",
		killer.." is the cartoon villian",
		"why is " ..extra.. " so.. bad?",
		extra.." went to go color and draw with his friends, but " ..killer.." ruined it.",
		"BAM! THERE GOES YOUR " ..extra,
		killer..", why are you killing afk people, huh?",
		extra.." asked God for the new Earth update, instead, the lightning strike got pushed to the main branch of his house.",
		killer.." I'll give you a cookie if you behave",
		extra.." CONGRATS YOU'VE lostttt",
		"so am i getting paid for writing thes-",
		extra.." was bopping along to the Techno",
		killer.." was surprised any gaming gets done going through " ..extra.."'s desk with ancient cup civilizations",
		extra.." said a yo mama joke",
		extra.." buddy... how do you manage that... YOU COULDVE DONE BETTER THAN THI",
		"this is the 200th line in the killfeed code, and Cole hasn't paid me yet. Send help.",
		extra.." got turned into a wikiHow article",
		killer.." hit the nux neutral special (its getting kicked from the gc again)",
		killer.." DELETED "..extra.."'s SERVER AND BANNED ALL HIS FRIENDS",
		extra.." deleted the github repository",
		extra.." got his google chrome chicken bone",
		"is "..extra.." and "..killer.." still frriieeendddsss",
		killer.." made sure "..extra.." had a happy and long-living life",
		extra.." sentenced to Colors' Catalog Avatar Creator Server",
		killer.." collected their pages....",
		extra.." peace",
		extra.." couldn't believe when "..killer.." said its "..killer.."ing' time",
		killer.." oh wait you actually won that. surprising.",
		killer.."ing' it",
		extra.." downloaded Genshin Impact",
		extra.." tried installing exploits in RS",
		extra.." tried killing god and failed",
		"WHO KILLED "..extra.." IN THE STORE?",
		--"The Shopkeeper killed "..extra.." for being bad",
		extra.." the unholy singular",
		extra.." sounded sus",
		killer.." lit it up",
		extra.." didn't take out the trash",
		extra.." knew what he meant",
		extra.." bro im bored",
		"the day they found " ..extra.." they hadn't yet been played",
		killer.." spoiled deltarune",
		extra.." reportedly trying to fight " ..killer,
		extra.." yo bro watch yo jet WATCH YO JET",
		extra.." SAW ULTRAKILL LAYER 8 REVEAL",
		extra.." was buddy holly",
		extra.." tried to explain the Colors Universe Lore",
		killer.." goog'd " ..extra,
		killer.." happy birthday",
		killer.." 360 degree noscope",
		extra.." wasn't hatsune miku",
		killer.." OH YEAH!",
		extra.." honk mimimimi",
		"something evil will happen to " ..extra,
		"hummus",
		extra.." used Adobe Products",
		-- jamer start
		extra.." tried using /emote",
		extra.." confronted the final boss",
		extra.." tried exploding " ..killer.."'s nuclear facility",
		extra.." got killed in kindergarten 3",
		extra.." tried cloning themselves",
		extra.." tried killing " ..killer.. " in cs",
		extra.." booted up cs source", --cole
		extra.." got nos'd", --cole
		extra.." tried making music for the first time",
		extra.." tried gaming on their ps4 at 3 am",
		extra.." has the loudest mechanical keyboard " ..killer.. " has heard in their LIFE", --cam
		extra.." has the loudest keyboard of all time", 
		extra.." met " ..killer.. " in the store.. they got crate'd",
		extra.." played content warning as a newbie in public randoms",
		extra.." hates cole", --cam
		"breaking news! " ..extra.. " found dead in corner of store.",
		extra.." played town and walked around after spawn protection",
		extra.." installed the wrong version of roblox",
		extra.." tried to kill the shady noob",
		extra.." tried to kill " ..killer,
		extra.." asked for free admin",
		extra.." stepped on a lego brick",
		killer.." swag?",
		extra.." stopped the boombox",
		killer.." asked extra what 9 + 10 is..." ..extra.. " said 21...",
		extra.." played overwatch",
		extra.." became british",
		extra.." tried to advertise his game on " ..killer.. "'s stream... yeah.. that didn't go well.",
		extra.." alright",
		killer.." had 1000 ping and pulled out the machete on extra",
		killer.." bought crate and started killing extra",
		extra.." was low on health and went out of the store",
		extra.." barely survived... but" ..killer.. " wasn't done yet...",
		extra.." bought 'common' for 5 souls but thought it was a new gun..",
		killer.." pushed " ..extra.. "'s snowman... and also killed" ..extra,
		extra.." missed the headshot",
		extra.." lost the tournament against " ..killer,
		extra.." got jumpscared by" ..killer,
		"DARN " ..extra.. "! BACK AT IT AGAIN!",
		extra.." inserted a free model into the game",
		-- jamer end 1
		extra.." lost the fight",
		-- jamer start 2
		extra.." played dead by daylight with " ..killer,
		extra.." pinged @everyone",
		extra.." started cringing",
		extra.." took " ..killer.. "'s sandvich",
		extra.." turned on light mode",
		extra.." copied " ..killer.. "'s homework",
		extra.." went to public lobbies and never came out",
		extra.." spent 300 dabloons on " ..killer.. "'s credit card",
		extra.." speedran death",
		killer.." speedran killing " ..extra,
		extra.." tried farming Souls but" ..killer.. " joined",
		extra.." tried loading " ..killer.. "'s tria os map",
		killer.." gave " ..extra.. " a taco",
		killer.." liked trees and tried sharing it with " ..extra,
		extra.." tried to swim in lava",
		killer.." had slain " ..extra,
		extra.." joined " ..killer.. "'s crossroads",
		extra.." accidentally unmuted in a call",
		extra.." was gex",
		extra.." tried to recreate the burning piano meme",
		extra.." asked killer for more wishes",
		extra.." played you have to eat 2000 crawfishes on mobile",
		extra.." tried to duplicate 224590 parts all at once in studio",
		killer.." played copyrighted music in front of " ..extra,
		extra.." played revolver showdown with " ..killer.. " in real life",
		extra.." tried to make a time machine but got electrified instead",
		extra.." accidentally fell down the stairs",
		extra.." gave a compliment to " ..killer.. ", " ..killer.. " didn't take it as a compliment though",
		extra.." played ultrakill and hated it",
		killer.." spoke taco bell to" ..extra,
		killer.." forced " ..extra.. " to become family friendly",
		extra.." bought amazon prime",
		extra.." forgot to update their windows 7",
		extra.." drank " ..killer.. "'s bloxy cola",
		extra.."'s company went on the stock market and it's going do- ohhh nooo......",
		extra.." tried making a YTP but made slop instead",
		killer.." forced " ..extra.. " to spend $15 each month",
		extra.." tried getting more RAM by downloading trojans",
		extra.." raised " ..killer.. " the wrong way",
		extra.." asked " ..killer.. " for revolver showdown's source code",
		extra.." tried speedrunning but got last place on the leaderboard",
		extra.." tried playing rock climbers irl and never came back",
		extra.." tried to swing the heaviest axe in history",
		extra.." drank too many energy drinks",
		extra.." forgot to save his project",
		extra.." wasted all their money on $30 plushies",
		killer.." killered " ..extra,
		extra.." tried to make his own search engine... but he forgot he can't code",
		extra.." tried downloading his entire desktop",
		extra.." tried becoming the next beluga... but his skill issue came.",
		extra.." bet his life on horse race tests... and he lost..",
		extra.." pirated copyrighted music and shared it with " ..killer,
		killer.." did workspace.extra:Destroy()",
		killer.." forced " ..extra.. " to go touch grass",
		killer.." flashbanged " ..extra.. " with local new = Instance.new('PointLight') new.Brightness = 10000",
		extra.." believed there was no game and left",
		extra.." tried to make " ..killer.. " believe that " ..extra.. " killed " ..killer.. "... that didn't go out well..",
		extra.." played dumb ways to die in real life",
		extra.."'s revolver showdown map got rejected",
		extra.." got replaced by " ..killer.. "AI",
		"hey!!" ..extra.. "!! " ..extra.. "??? where did " ..extra.. " go?",
		extra.." followed roblox studio tutorials",
		extra.." pirated a game but " ..killer.. " caught them doing it",
		killer.." gave " ..extra.. " a zip bomb",
		extra.." woke up and thought it was morning and started gaming but had their volume on max",
		extra.." tried to use a totem of undying against " ..killer,
		extra.." got banned from the server",
		extra.." died and " ..killer.. "'s stream chat spammed 'F'",
		-- jamer end 3
		extra.." died in a fire",
		killer.." took " ..extra.. " apart",  -- thanks colors for these amazing killfeeds at 6 in the morning :desolated:
		-- jamer start 4
		killer.." pefectly timed " ..extra.. "'s death with a 2015 minecraft intro",
		extra.." accidentally put on the real springlock suit",
		extra.." wore the worst outfit at " ..killer.. "'s party and " ..killer.. " asked " ..extra.. " to come to the back",
		extra.." sent memes in '#general' when there was #memes",
		killer.." reported " ..extra.. "'s message for no reason",
		extra.." clicked on " ..killer.. "'s ad",
		killer.." screamed into their mic while" ..extra.. " and " ..killer.. " were calling",
		killer.." spammed their soundboard on a call with extra",
		extra.." tried to get new hair for free at " ..killer.. "'s game. 1 week after start they quit.",
		extra.." changed their outfit to the halloween version when it was summer",
		extra.." went to mckillers and ordered a whopper",
		extra.." ordered pineapple pizza at " ..killer.. "'s restaurant",
		extra.." started a chase and " ..killer.. " was helping and they said 'go right' but then 'no wait my bad'",
		extra.." downloaded the wrong version of " ..killer.. "'s game",
		extra.." tried rickrolling " ..killer.. " but failed",
		extra.." tried spoiling the story of " ..killer.. "'s game",
		extra.." tried finishing " ..killer.. "'s desert bus",
		extra.." played five nights at " ..killer.. "'s and lost",
		extra.." accepted that " ..killer.. " killed them and started raging",
		extra.." used x-ray in " ..killer.. "'s minecraft server and got banned",
		extra.." tried dragging an ingame un-draggable window around",
		extra.." said a dad joke to " ..killer,
		extra.." played calculator and lost",
		extra.." ate a lego made by " ..killer,
		extra.." spelt " ..killer.. "'s name backwards",
		extra.." fought the final boss..." ..killer.. "...",
		killer.." eternally forced extra to push 5 boulders up mount everest",
		killer.." g-forced " ..extra,
		killer.." stole " ..extra.. "'s intelligence",
		extra.." wasn't a standing citizen",
		extra.." tried saying a yo mama joke in the big '25",
		killer.." deleted " ..extra.. "'s wifi and forced them to go to the mcdonald's wifi",
		-- jamer end 4 FINALLY ITS OVR
		extra.." was going prime on this beat",
		"why was" ..killer.. "... blue..?",
		killer.." had 20 dollars in their pocket",
		-- jamer start 5 | why
		extra.. "accepted that " ..killer.. "killed them and started raging",
		extra.. "used x-ray in" ..killer.. " 's minecraft server",
		extra.. "tried dragging an ingame undraggable window around",
		extra.. "said a dad joke to " ..killer,
		extra.. "played calculator and lost",
		extra.. "ate a lego made by " ..killer,
		extra.. "spelt " ..killer.. " 's name backwards",
		extra.. "fought the final boss..." ..killer.. "...",
		killer.. "eternally forced " ..extra.. " to push 5 boulders up mount everest",
		killer.. "stole " ..extra.. " 's intelligence",
		extra.. "wasnt a standing citizen",
		extra.. "tried saying a yo mama joke in the big 25",
		killer.. "deleted " ..extra.. " 's wifi and forced them to use the mcdonalds WiFi",
		"INTRUDER ALERT:" ..killer.. " IN BASE! ALERT: The" ..killer.. " has taken our intelligence.",
		extra.. "didnt like " ..killer.. " 's pancakes",
		extra.. "challenged the " ..killer.. " jockey... you might know what happend after",
		":bucktoof: -" ..extra.. "(before the" ..killer..")",
		":oh_no: -" ..extra.. "(after the" ..killer..")",
		extra.. "said they were emo but" ..killer.. " saw right through the lies.",
		extra.. "ordered something not on the menu",
		killer.. " did the workspace.extra.Humanoid.Health = 0",
		extra.. " touched the ghostwalker and wasnt worthy",
		extra.. " was playing forsaken until" ..killer.. " was the " ..killer,
		extra.. " forgot the final script that made everything come together in their game...",
		extra.. " thought they could beat" ..killer.. "'s tria.os level... they never came back.",
		extra.. " used AI to make their essay in " ..killer.. "'s class and submitted it... it didnt go well.",
		extra.. " YOU'RE STARTING TO MAKE MY BRAIN GO BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR *explosion*",
		extra.. "'s job application got rejected by " ..killer,
		extra.. " overslept",
		extra.. " bought a website domain just to abandon it after a week",
		extra.. " made AI memes but " ..killer.. " didnt laugh.",
		extra.. " played killeratro. they lost immediately.",
		extra.. " ate " ..killer.. "'s saved up leftovers",
		"added: " ..extra.."," ..killer..": deleted Model, " ..extra,
		extra.. " sent a DM to" ..killer.. " at 3 am",
		extra.. " tried scratch but didnt understand anything",
		extra.. " got bit by " ..killer.. "'s mosquito",
		extra.. " tried SFM but still didnt understand anything",
		extra.. " turned on " ..killer.."'s phone on 3 am but the brightness was set to max with bright mode",
		killer.. " broke " ..extra.."'s map",
		"killer if you kill extra i will give you 10 bucks, " ..killer..":",
		extra.. "<" ..killer,
		"somebody stop me im smoking the track",
		"ill revolver " ..extra.. " and",
		"make more sons of the " ..killer.."s",
		"ill jim carrey your " ..extra.. " through the door",
		"welcome to the tutorial on how to kill " ..extra.."!",
		extra.. " GEEKED " ..killer.. " LOCKED IN",
		"holy moly lois! " ..extra.."'s ugly.",
		extra.. " became history",
		killer.. " VS " ..extra.. " rap battle!",
		-- jamer end 5 | oh m god its over br
		extra.. " geeked out",
		extra.. " evaded jury duty",
		extra.. " lived a smiling friends episode irl",
		extra.. " divided by 0"
	}
